# Generated by Django 3.2.23 on 2024-03-02 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='cmp_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('photo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('usertype', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=10)),
                ('Etime', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('date', models.CharField(default=1, max_length=50)),
                ('CUSTOMER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=10)),
                ('latitude', models.CharField(default=1, max_length=250)),
                ('longitude', models.CharField(default=2, max_length=250)),
                ('additionalinfo', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=75)),
                ('min_wage', models.CharField(max_length=50)),
                ('CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.category')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Workerscomplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('cdate', models.CharField(max_length=10)),
                ('reply', models.CharField(max_length=100)),
                ('rdate', models.CharField(max_length=10)),
                ('WORKER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.worker')),
            ],
        ),
        migrations.CreateModel(
            name='UserComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('cdate', models.CharField(max_length=10)),
                ('ctime', models.CharField(max_length=10)),
                ('reply', models.CharField(max_length=300)),
                ('rdate', models.CharField(max_length=10)),
                ('rtime', models.CharField(max_length=10)),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('status', models.CharField(default=1, max_length=20)),
                ('WORKER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workapp.worker')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('review', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('CUSTOMER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workapp.customer')),
                ('WORKER', models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='workapp.worker')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('ORDER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workapp.order')),
                ('WORKER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workapp.worker')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='SCHEDULE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workapp.schedule'),
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('CUSTOMER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workapp.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.login'),
        ),
        migrations.CreateModel(
            name='blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUSTOMER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workapp.customer')),
                ('WORKER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workapp.worker')),
            ],
        ),
    ]
